# SwiftLint Configuration for PawNova
# Modern Swift best practices for iOS 17+

# Paths to include/exclude
included:
  - Project PawNova
excluded:
  - Pods
  - build
  - DerivedData
  - .build
  - vendor

# Opt-in rules (modern Swift features)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules (too strict for rapid development)
disabled_rules:
  - todo # Allow TODOs during development
  - line_length # SwiftUI can have long view chains
  - function_body_length # SwiftUI views can be long
  - type_body_length # SwiftUI views with many subviews
  - file_length # OK for now during early development

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - i
    - j
    - r  # RGB color components
    - g
    - b
    - a  # Alpha channel
    - s  # Seconds (time formatting)

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - URL
    - Project_PawNovaApp  # Xcode-generated app entry point

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# SwiftUI-specific
trailing_comma:
  mandatory_comma: true

# Severity levels
force_cast: warning
force_try: warning
force_unwrapping: warning

# Modern Swift conventions
implicit_return:
  included:
    - closure
    - function
    - getter

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '(?<!\/\/)\bprint\('
    message: "Use proper logging instead of print()"
    severity: warning

  async_await_over_completion:
    name: "Prefer async/await over completion handlers"
    regex: '@escaping\s*\(\s*.*\s*->\s*Void\s*\)'
    message: "Consider using async/await instead of completion handlers"
    severity: warning

# Reporter
reporter: "xcode"
